# Generated by Django 6.0.2 on 2026-02-16 13:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScopePolicy',
            fields=[
                ('scope_policy_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='default-policy', max_length=100)),
                ('allowed_hosts', models.JSONField(blank=True, default=list)),
                ('max_runs', models.IntegerField(blank=True, null=True)),
                ('created_runs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_url', models.URLField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scope_policy', models.ForeignKey(blank=True, db_column='scope_policy_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_runs', to='api.scopepolicy')),
            ],
        ),
    ]
