# Generated by Django 6.0.2 on 2026-02-19 07:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceBlob',
            fields=[
                ('blob_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(default='text/plain', max_length=255)),
                ('storage_ref', models.CharField(default='stub://storage', max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='candidate', max_length=255)),
                ('severity_raw', models.CharField(default='info', max_length=32)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='api.scanrun')),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('finding_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='finding', max_length=255)),
                ('severity_raw', models.CharField(default='info', max_length=32)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='api.scanrun')),
            ],
        ),
        migrations.CreateModel(
            name='FindingEvidenceLink',
            fields=[
                ('link_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(default='evidence', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blob', models.ForeignKey(db_column='blob_id', on_delete=django.db.models.deletion.CASCADE, related_name='finding_links', to='api.evidenceblob')),
                ('finding', models.ForeignKey(db_column='finding_id', on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='api.finding')),
            ],
        ),
        migrations.CreateModel(
            name='RequestCatalogItem',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(default='GET', max_length=16)),
                ('url', models.CharField(default='/', max_length=2048)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.CASCADE, related_name='request_catalog_items', to='api.scanrun')),
            ],
        ),
    ]
