# Generated by Django 6.0.2 on 2026-02-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('verifying', 'Verifying'), ('confirmed', 'Confirmed'), ('false_positive', 'False Positive'), ('dismissed', 'Dismissed')], default='open', max_length=16),
        ),
    ]
