# Generated by ChatGPT for P5 report artifacts
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_candidate_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunReport",
            fields=[
                ("report_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("markdown", models.TextField()),
                ("json", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="api.scanrun",
                    ),
                ),
            ],
            options={
                "db_table": "run_reports",
            },
        ),
    ]