# Generated by Django 6.0.2 on 2026-04-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_embedding_dim_768'),
    ]

    operations = [
        migrations.AddField(
            model_name='payloadpattern',
            name='sub_technique',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
