# Generated by Django 6.0.2 on 2026-04-14 04:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_sub_technique_to_payloadpattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanrun',
            name='mode',
            field=models.CharField(choices=[('hybrid-max', 'Hybrid Max'), ('hybrid-lite', 'Hybrid Lite'), ('discovery', 'Discovery')], default='hybrid-lite', max_length=16),
        ),
        migrations.CreateModel(
            name='DiscoveryNode',
            fields=[
                ('node_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('depth', models.IntegerField(default=0)),
                ('node_type', models.CharField(choices=[('target', 'Target'), ('endpoint', 'Endpoint'), ('vuln', 'Vuln'), ('clue', 'Clue'), ('exploit_step', 'Exploit Step'), ('flag', 'Flag'), ('dead_end', 'Dead End')], max_length=32)),
                ('endpoint', models.CharField(blank=True, max_length=512, null=True)),
                ('vuln_type', models.CharField(blank=True, max_length=64, null=True)),
                ('summary', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('exploring', 'Exploring'), ('explored', 'Explored'), ('dead_end', 'Dead End'), ('confirmed', 'Confirmed')], default='pending', max_length=16)),
                ('worker_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('explored_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.discoverynode')),
                ('scan_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='api.scanrun')),
            ],
            options={
                'db_table': 'discovery_nodes',
                'indexes': [models.Index(fields=['scan_run', 'status', '-depth', 'created_at'], name='discovery_n_scan_ru_de435f_idx')],
            },
        ),
    ]
