# Generated by Django 6.0.2 on 2026-04-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_discovery_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadend',
            name='simhash',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='payloadpattern',
            name='simhash',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
