# Generated by Django 6.0.2 on 2026-04-17 06:57

import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_simhash_to_payload_pattern_and_dead_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanrun',
            name='mode',
            field=models.CharField(choices=[('hybrid-max', 'Hybrid Max'), ('hybrid-lite', 'Hybrid Lite'), ('discovery', 'Discovery')], default='discovery', max_length=16),
        ),
        migrations.CreateModel(
            name='EndpointSpec',
            fields=[
                ('spec_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_host', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(max_length=8)),
                ('endpoint', models.TextField()),
                ('params_schema', models.JSONField(blank=True, null=True)),
                ('headers_required', models.JSONField(blank=True, null=True)),
                ('auth_required', models.BooleanField(default=False)),
                ('response_shape', models.JSONField(blank=True, null=True)),
                ('suspected_vuln_types', models.JSONField(blank=True, null=True)),
                ('sink_hints', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('times_seen', models.IntegerField(default=1)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'endpoint_specs',
                'indexes': [models.Index(fields=['target_host', 'last_seen_at'], name='endpoint_sp_target__768c80_idx')],
                'unique_together': {('target_host', 'method', 'endpoint')},
            },
        ),
    ]
