# Generated by Django 6.0.2 on 2026-04-22 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_endpoint_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmtrace',
            name='target_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traces', to='api.discoverynode'),
        ),
    ]
