# Generated by Codex on 2026-05-22

from django.db import migrations, models


BASE_SCORE_BY_TYPE = {
    "target": 0.35,
    "endpoint": 0.45,
    "clue": 0.55,
    "vuln": 0.72,
    "exploit_step": 0.88,
    "flag": 1.0,
    "dead_end": 0.05,
}

QUEUE_LANES_BY_TYPE = {
    "target": "recon",
    "endpoint": "endpoint",
    "vuln": "hypothesis",
    "clue": "hypothesis",
    "exploit_step": "chain",
    "flag": "proof",
    "dead_end": "report",
}


def backfill_queue_metadata(apps, schema_editor):
    DiscoveryNode = apps.get_model("api", "DiscoveryNode")
    for node in DiscoveryNode.objects.all().iterator():
        queue_lane = QUEUE_LANES_BY_TYPE.get(node.node_type, "hypothesis")
        node.queue_lane = queue_lane
        node.priority_score = BASE_SCORE_BY_TYPE.get(node.node_type, 0.45) + min(max(node.depth, 0) * 0.025, 0.2)
        node.score_breakdown = {
            "base": BASE_SCORE_BY_TYPE.get(node.node_type, 0.45),
            "depth_bonus": min(max(node.depth, 0) * 0.025, 0.2),
            "migration_backfill": True,
        }
        node.provider_hint = "codex" if queue_lane in {"proof", "recheck", "report"} else "claude"
        node.mission = {
            "lane": queue_lane,
            "objective": "Continue this DiscoveryNode using Watchdog queue rules.",
            "success_criteria": [
                "record_trace includes meaningful tool_calls",
                "new discoveries are pushed before testing",
                "final status is explored, confirmed, or dead_end",
            ],
        }
        node.save(update_fields=[
            "queue_lane",
            "priority_score",
            "score_breakdown",
            "provider_hint",
            "mission",
        ])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_llmtrace_target_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoverynode",
            name="queue_lane",
            field=models.CharField(blank=True, default="hypothesis", max_length=32),
        ),
        migrations.AddField(
            model_name="discoverynode",
            name="priority_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="discoverynode",
            name="score_breakdown",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discoverynode",
            name="lease_owner",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="discoverynode",
            name="leased_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discoverynode",
            name="attempt_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="discoverynode",
            name="blocked_by",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="discoverynode",
            name="provider_hint",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="discoverynode",
            name="mission",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(backfill_queue_metadata, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="discoverynode",
            index=models.Index(fields=["scan_run", "status", "-priority_score", "-depth", "created_at"], name="discovery_n_scan_r_3ad0ee_idx"),
        ),
        migrations.AddIndex(
            model_name="discoverynode",
            index=models.Index(fields=["scan_run", "queue_lane", "status", "-priority_score"], name="discovery_n_scan_r_3b00e7_idx"),
        ),
    ]
