"""Exploit technique seed — loads .md files from techniques/ directory.

Each .md file in techniques/<vuln_type>/ becomes one PayloadPattern row
(source='technique') in the DB.  YAML frontmatter carries structured fields;
Markdown body becomes the human/LLM-readable technique description stored in
attack_metadata.

Directory layout:
  techniques/
    xss/
      dom_xss_event_handler.md
    sqli/
      union_based_sqli.md
    learned/           ← auto-generated by export_learned
      ...
    ...

Usage:
  docker compose exec backend python manage.py seed_techniques
  docker compose exec backend python manage.py seed_techniques --reset
  docker compose exec backend python manage.py seed_techniques --dry-run
"""
from __future__ import annotations

import os
import re
from pathlib import Path

import yaml
from django.core.management.base import BaseCommand
from django.db import transaction

from api.embedding_service import (
    EMBEDDING_MODEL,
    embed_documents,
    is_available as embeddings_available,
)
from api.models import PayloadPattern, VulnerabilityEntry

TECHNIQUES_DIR = Path(__file__).resolve().parent / "techniques"


def _parse_md(filepath: Path) -> dict | None:
    """Parse a technique .md file into a TECHNIQUES-compatible dict."""
    text = filepath.read_text(encoding="utf-8")

    # Split YAML frontmatter and body
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n(.*)", text, re.DOTALL)
    if not m:
        return None
    try:
        front = yaml.safe_load(m.group(1))
    except yaml.YAMLError:
        return None
    if not front or not isinstance(front, dict):
        return None
    body = m.group(2).strip()

    name = front.get("name")
    vuln_type = front.get("vuln_type")
    if not name or not vuln_type:
        return None

    # Parse Markdown sections
    sections = _split_sections(body)

    title = sections.get("_title", name.replace("_", " ").title())
    applies_when = sections.get("when to apply", "")
    prerequisites = _parse_list(sections.get("prerequisites", ""))
    steps_md = sections.get("steps", "")
    code_template = _extract_code_block(sections.get("code template", ""))
    examples_raw = sections.get("examples", "")
    examples = _parse_examples(examples_raw)
    tags = front.get("tags", [])

    return {
        "name": name,
        "vuln_type": vuln_type,
        "sub_technique": front.get("sub_technique"),
        "category": front.get("category", "exploitation"),
        "safety_level": front.get("safety_level", "safe"),
        "tags": tags,
        "attack_metadata": {
            "kind": "exploit_technique",
            "name": title,
            "applies_when": applies_when,
            "prerequisites": prerequisites,
            "technique_steps_md": steps_md,
            "code_template": code_template,
            "examples": examples,
            "tags": tags,
        },
    }


def _split_sections(body: str) -> dict[str, str]:
    """Split Markdown body into sections by ## headers."""
    result = {}
    # Extract title (# header)
    title_m = re.match(r"^#\s+(.+)", body)
    if title_m:
        result["_title"] = title_m.group(1).strip()

    current_section = None
    lines: list[str] = []
    for line in body.split("\n"):
        header_m = re.match(r"^##\s+(.+)", line)
        if header_m:
            if current_section is not None:
                result[current_section] = "\n".join(lines).strip()
            current_section = header_m.group(1).strip().lower()
            lines = []
        elif current_section is not None:
            lines.append(line)

    if current_section is not None:
        result[current_section] = "\n".join(lines).strip()

    return result


def _parse_list(text: str) -> list[str]:
    """Parse a Markdown bullet list into a Python list."""
    items = []
    for line in text.split("\n"):
        m = re.match(r"^[-*]\s+(.+)", line.strip())
        if m:
            items.append(m.group(1).strip())
    return items


def _extract_code_block(text: str) -> str:
    """Extract content from a fenced code block, or return raw text."""
    m = re.search(r"```\w*\n(.*?)```", text, re.DOTALL)
    if m:
        return m.group(1).strip()
    return text.strip()


def _parse_examples(text: str) -> list[dict]:
    """Parse examples section into structured list."""
    if not text.strip():
        return []

    examples = []
    # Split by ### Example N
    parts = re.split(r"###\s+Example\s+\d+", text)
    for part in parts:
        part = part.strip()
        if not part:
            continue
        params = {}
        notes_lines = []
        for line in part.split("\n"):
            param_m = re.match(r"^[-*]\s+\*\*(\w+)\*\*:\s*(.+)", line.strip())
            if param_m:
                key = param_m.group(1)
                val = param_m.group(2).strip()
                # Try to parse JSON values (lists, dicts)
                if val.startswith("`") and val.endswith("`"):
                    val = val[1:-1]
                    try:
                        import json
                        val = json.loads(val)
                    except (json.JSONDecodeError, ValueError):
                        pass
                params[key] = val
            elif line.strip() and not line.strip().startswith("###"):
                notes_lines.append(line.strip())
        notes = " ".join(notes_lines).strip()
        example = {}
        if params:
            example["params"] = params
        if notes:
            example["notes"] = notes
        if example:
            examples.append(example)

    return examples


def load_techniques(base_dir: Path | None = None) -> list[dict]:
    """Load all .md technique files from the techniques directory."""
    root = base_dir or TECHNIQUES_DIR
    techniques = []
    if not root.is_dir():
        return techniques

    for md_path in sorted(root.rglob("*.md")):
        t = _parse_md(md_path)
        if t:
            techniques.append(t)
    return techniques


class Command(BaseCommand):
    help = "Seed exploit techniques from techniques/*.md files"

    def add_arguments(self, parser):
        parser.add_argument(
            "--reset", action="store_true",
            help="Delete all existing source='technique' entries and re-seed",
        )
        parser.add_argument(
            "--dry-run", action="store_true",
            help="Parse and show techniques without writing to DB",
        )
        parser.add_argument(
            "--dir", type=str, default=None,
            help="Override techniques directory path",
        )

    @transaction.atomic
    def handle(self, *args, **opts):
        base_dir = Path(opts["dir"]) if opts.get("dir") else None
        techniques = load_techniques(base_dir)

        self.stdout.write(f"Loaded {len(techniques)} techniques from .md files\n")

        if opts.get("dry_run"):
            for t in techniques:
                self.stdout.write(f"  [{t['vuln_type']:24s}] {t['name']}")
            self.stdout.write(self.style.SUCCESS(f"\nDry run: {len(techniques)} techniques parsed"))
            return

        if opts.get("reset"):
            deleted = PayloadPattern.objects.filter(source="technique").delete()
            self.stdout.write(self.style.WARNING(f"reset: deleted {deleted}"))

        vuln_by_type: dict[str, VulnerabilityEntry] = {
            v.vuln_type: v for v in VulnerabilityEntry.objects.all()
        }

        created_cnt = 0
        updated_cnt = 0
        for t in techniques:
            vuln = vuln_by_type.get(t["vuln_type"])
            obj, created = PayloadPattern.objects.update_or_create(
                name=t["name"],
                source="technique",
                defaults={
                    "vulnerability": vuln,
                    "vuln_type": t["vuln_type"],
                    "sub_technique": t.get("sub_technique"),
                    "category": t.get("category", "exploitation"),
                    "safety_level": t.get("safety_level", "safe"),
                    "request_template": "",
                    "matcher": None,
                    "safety_notes": t["attack_metadata"].get("applies_when", "")[:500],
                    "tags": t.get("tags", []),
                    "attack_metadata": t["attack_metadata"],
                    "is_active": True,
                },
            )
            fk_mark = "FK" if vuln else "!!"
            self.stdout.write(
                f"  technique {'+' if created else '='} [{fk_mark}] {t['name']:40s} ({t['vuln_type']})"
            )
            if created:
                created_cnt += 1
            else:
                updated_cnt += 1

        self.stdout.write(self.style.SUCCESS(
            f"\ntechniques: +{created_cnt} created, ={updated_cnt} updated"
        ))

        if embeddings_available():
            from api.embedding_service import pattern_text
            targets = list(PayloadPattern.objects.filter(source="technique"))
            texts = []
            for p in targets:
                meta = p.attack_metadata or {}
                parts = [
                    f"name: {meta.get('name', p.name)}",
                    f"vuln_type: {p.vuln_type}",
                    f"applies_when: {meta.get('applies_when', '')}",
                    f"prerequisites: {' / '.join(meta.get('prerequisites') or [])}",
                    f"steps: {meta.get('technique_steps_md', '')[:500]}",
                    f"tags: {', '.join(meta.get('tags') or p.tags or [])}",
                ]
                texts.append("\n".join(parts))
            self.stdout.write(f"embedding {len(texts)} techniques via {EMBEDDING_MODEL} ...")
            vectors = embed_documents(texts)
            if vectors:
                for p, vec in zip(targets, vectors):
                    p.embedding = vec
                    p.embedding_model = EMBEDDING_MODEL
                    p.save(update_fields=["embedding", "embedding_model"])
                self.stdout.write(self.style.SUCCESS(
                    f"embeddings saved for {len(vectors)} techniques"
                ))
            else:
                self.stdout.write(self.style.WARNING("Embedding generation failed — skipping"))
        else:
            self.stdout.write(self.style.WARNING(
                "Embedding model not available — semantic search will be disabled"
            ))
